server:
  port: ${PORT:8081}
  address: 0.0.0.0
  ssl:
    enabled: false
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/customer-service}

spring:
  logging:
    config: classpath:logback-spring.xml
  application:
    name: ${APPLICATION_NAME:customer-service}
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/customer-service
    username: postgres
    password: postgres

    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect  # Cần thêm dòng này
      hibernate.format_sql: true  # Để dễ dàng đọc SQL trong log
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

#    properties:
#      hibernate:
#        '[default_schema]': ${PG_SCHEMA:customer-service}

eureka:
  client:
    service-url:
      defaultZone: http://10.0.106.104:8761/eureka
    register-with-eureka: true
    fetch-registry: true

spring-doc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true

logging:
  level:
    root: debug
