server:
  port: ${PORT:8080}
  ssl:
    enabled: false
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/customer-service}
spring:
  application:
    name: ${APPLICATION_NAME:customer-service}
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/customer-service
    username: postgres
    password: postgres

    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        '[default_schema]': ${PG_SCHEMA:customer-service}
spring-doc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true



#logging:
#  level:
#    root: debug
